### ISSUE TITLE
Error when using the family filter with vase-0.4.1

### ISSUE THREAD

**Issue by Ax-Sch** [gantzgraf/vase#1]
Dear David,
First - thank you for your program vase - it's great !
With the current version (0.4.1) the files attached raise an error, when executing the following command:
`vase -i test.vcf --de_novo -o test --ped test.ped`

The error message is:
`  File "/home/aschmidt/.local/bin/vase", line 1385, in <module>`  
`   vase_runner.run()`
`  File "/home/aschmidt/.local/lib/python3.7/site-packages/vase/vase_runner.py", line 298, in run`
`   self.process_record(vase_record)`
`  File "/home/aschmidt/.local/lib/python3.7/site-packages/vase/vase_runner.py", line 361, in process_record`
`    record, dom_filter_alleles, filter_csq)`
`  File "/home/aschmidt/.local/lib/python3.7/site-packages/vase/family_filter.py", line 1189, in process_record`
`    sv.annotate_record(self.report_file, self.annot_fields)`
`  File "/home/aschmidt/.local/lib/python3.7/site-packages/vase/family_filter.py", line 1340, in annotate_record`
`    self.segregant.record.info[k] = v`
`  File "pysam/libcbcf.pyx", line 2586, in pysam.libcbcf.VariantRecordInfo.__setitem__`
`  File "pysam/libcbcf.pyx", line 689, in pysam.libcbcf.bcf_info_set_value`
`  File "pysam/libcbcf.pyx", line 585, in pysam.libcbcf.bcf_check_values`
`TypeError: values expected to be 4-tuple, given len=7`

When using vase-0.2.4 no error occured. 

I attached an extra .txt extension to both files, otherwise I was not able to upload them. Can you reproduce this error?
[test.ped.txt](https://github.com/david-a-parry/vase/files/5318595/test.ped.txt)
[test.vcf.txt](https://github.com/david-a-parry/vase/files/5318596/test.vcf.txt)

Best regards
Axel

**Comment by david-a-parry** [comment]
Hi Axel,

Thank you for raising this issue and I'm glad you like vase.

I think I can see what's causing this problem. The issue seems to be specific to multiallelic variants either when there are no VEP annotations in the VCF input or if the VEP consequence is an 'intergenic_variant'. A quick workaround would be to restrict to biallelic variants (e.g. `vase --max_alt 1 ...`) but I will try and get a fix out ASAP.

Best

Dave

**Comment by david-a-parry** [comment]
Hi Axel,

This issue should be fixed in the main branch now.

There is a small issue with your input file. Because it does not have any INFO headers this causes an issue with pysam not knowing how to handle the INFO fields when trying to output the record, so I have attached a version with dummy INFO fields that should allow you to confirm the fix at your end once you've updated vase.

Dave

[test_with_info_headers.vcf.gz](https://github.com/david-a-parry/vase/files/5326425/test_with_info_headers.vcf.gz)

**Comment by Ax-Sch** [comment]
Hi Dave,

I just updated vase and tried it - it works well without any issues now.

Thank you,
Axel
